### ISSUE TITLE
iOS and Android Browser Support?

### ISSUE THREAD

**Issue by chrimm** [JohnLouderback/GDB#24]
Hi John!

I'm currently considering whether to use GDB in a Cordova/PhoneGap Web-app. Is there any information regarding the support on mobile browser as Mobile Safari on iOS and the Android OS's Browser, yet?

Any information will be appreciated!

Thanks!
—Chris

**Comment by JohnLouderback** [comment]
In my experience, it works in iOS and Android. I have not found any bugs thus far that contradict that. Let me know if you need any help, or have questions. I hope the plugins does everything you need it to do.

Thanks,
-John
